### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by Cat-Vader** [gTahidi/gTahidi-Beta#17]
@amosmachora If MSAL is an issue, we could temporarily switch providers. I have initialized the cosmos DB MongoDB (API), We can work with storing user info from that end.

**Comment by amosmachora** [comment]
Gotchya bro

**Comment by Cat-Vader** [comment]
We can also Use Sweep AI to look at and refactor the code if necessary check it out

**Comment by amosmachora** [comment]
Created auth for some identity providers. only thing remaining is email and password. However before production @ Cat-Vader you should create a bunch of client ids and secrets. Ask me how.

**Comment by Cat-Vader** [comment]
Ill get into it, any other specificities needed?

________________________________

**Comment by Cat-Vader** [comment]
@kechykechy @amosmachora Still cant navigate to auth page in the deployed version This is the subdomain config
https://www.gtahidiai.com/api/auth/error?error=Configuration
I will attach full logs

**Comment by Cat-Vader** [comment]
auth solved
